# Generated by Django 5.2.8 on 2025-12-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtrackerapp', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
